pool:
  vmImage: windows-latest

trigger:
  paths:
    include:
    # Only trigger on update of `current.zip`
    - current.zip

resources:
  repositories:
    - repository: dumped-cs
      type: github
      endpoint: RaenonX-PokemonTCGP
      name: RaenonX-PokemonTCGP/pokemon-tcgp-dumped-cs

variables:
  - template: variables/main.yml

stages:
- stage: DumpCS
  jobs:
    - job: DumpCS
      displayName: Dump C#
      steps:
        - template: templates/setup.yml

        - task: ExtractFiles@1
          displayName: 'Extract Binary ZIP'
          inputs:
            archiveFilePatterns: $(REPO_APK_DUMPER_ABS_DIR)/current.zip
            destinationFolder: $(REPO_APK_DUMPER_ABS_DIR)
            cleanDestinationFolder: false

        - powershell: |
            Get-FileHash .\libil2cpp.so -Algorithm MD5
            Get-FileHash .\global-metadata.dat -Algorithm MD5
          displayName: 'Print File Hash'
          workingDirectory: $(REPO_APK_DUMPER_ABS_DIR)

        - powershell: |
            .\.tool\Cpp2IL-af5217c.exe `
              --force-binary-path .\libil2cpp.so `
              --force-metadata-path .\global-metadata.dat `
              --force-unity-version 2022.3.22f1 `
              --output-as diffable-cs `
              --output-to "$(CPP_DUMP_OUTPUT_DIR)"
          displayName: 'Dump C# files'
          workingDirectory: $(REPO_APK_DUMPER_ABS_DIR)

        - powershell: |
            Copy-Item `
              -Path "$(CPP_DUMP_OUTPUT_DIR)\DiffableCs\PSMain\*" `
              -Destination "$(DUMPED_CS_DIR)" `
              -Force `
              -Recurse
          displayName: 'Copy dumped C# files'
          workingDirectory: $(REPO_APK_DUMPER_ABS_DIR)

        - task: PowerShell@2
          displayName: Cleanup Dump Metadata
          inputs:
            filePath: '$(REPO_APK_DUMPER_ABS_DIR)\.tool\Cleanup-Meta.ps1'
            arguments: '-CsFileDir $(DUMPED_CS_DIR)'
            showWarnings: true
            pwsh: true

        - task: PowerShell@2
          displayName: Commit C# Dump Changes
          inputs:
            targetType: 'inline'
            script: |
              $Version = $(Get-Content -Path "$(REPO_APK_DUMPER_ABS_DIR)\current-version.txt")
              git checkout main
              git add .
              git commit -m "Updated C# dumps to $Version by $(Build.Repository.Name)@$(Build.SourceVersion)" || echo "No changes to commit"
              git push origin main
            showWarnings: true
            workingDirectory: $(REPO_DUMPED_CS_ABS_DIR)
            pwsh: true
